/**
 * Role → permissions matrix.
 */
import { PERMISSION, ROLE, type Permission, type Role } from '@bazar/constants';

const CUSTOMER: readonly Permission[] = [
  PERMISSION.ORDER_READ,
  PERMISSION.ORDER_CREATE,
  PERMISSION.ORDER_CANCEL,
  PERMISSION.PRODUCT_READ,
  PERMISSION.STORE_READ,
  PERMISSION.PAYMENT_READ,
];

const COURIER: readonly Permission[] = [
  PERMISSION.ORDER_READ,
  PERMISSION.DELIVERY_READ,
  PERMISSION.DELIVERY_ACCEPT,
  PERMISSION.DELIVERY_COMPLETE,
  PERMISSION.STORE_READ,
  PERMISSION.PRODUCT_READ,
];

const VENDOR: readonly Permission[] = [
  PERMISSION.ORDER_READ,
  PERMISSION.ORDER_UPDATE,
  PERMISSION.PRODUCT_READ,
  PERMISSION.PRODUCT_WRITE,
  PERMISSION.STORE_READ,
  PERMISSION.STORE_WRITE,
  PERMISSION.PAYMENT_READ,
  PERMISSION.ANALYTICS_READ,
];

/** Support/dispatch desk: sees everything operational, touches no settings or money rules. */
const OPERATOR: readonly Permission[] = [
  PERMISSION.ORDER_READ,
  PERMISSION.ORDER_READ_ANY,
  PERMISSION.ORDER_UPDATE,
  PERMISSION.ORDER_CANCEL,
  PERMISSION.ORDER_ASSIGN,
  PERMISSION.DELIVERY_READ,
  PERMISSION.COURIER_READ,
  PERMISSION.CUSTOMER_READ,
  PERMISSION.STORE_READ,
  PERMISSION.VENDOR_READ,
  PERMISSION.PRODUCT_READ,
  PERMISSION.PAYMENT_READ,
  PERMISSION.SUPPORT_HANDLE,
  PERMISSION.ANALYTICS_READ,
];

const ADMIN: readonly Permission[] = [
  ...OPERATOR,
  PERMISSION.PRODUCT_WRITE,
  PERMISSION.CATEGORY_WRITE,
  PERMISSION.STORE_WRITE,
  PERMISSION.VENDOR_WRITE,
  PERMISSION.COURIER_WRITE,
  PERMISSION.USER_READ,
  PERMISSION.USER_WRITE,
  PERMISSION.PAYMENT_REFUND,
  PERMISSION.PRICING_WRITE,
  PERMISSION.PROMOTION_WRITE,
  PERMISSION.GEO_WRITE,
  PERMISSION.AUDIT_READ,
  PERMISSION.SETTINGS_WRITE,
];

/** SUPER_ADMIN is the only role that may cross tenants and edit tenants themselves. */
const SUPER_ADMIN: readonly Permission[] = [...ADMIN, PERMISSION.TENANT_WRITE];

export const ROLE_PERMISSIONS: Record<Role, readonly Permission[]> = {
  [ROLE.CUSTOMER]: CUSTOMER,
  [ROLE.COURIER]: COURIER,
  [ROLE.VENDOR]: VENDOR,
  [ROLE.OPERATOR]: OPERATOR,
  [ROLE.ADMIN]: ADMIN,
  [ROLE.SUPER_ADMIN]: SUPER_ADMIN,
};

/** Union of the permissions granted by every role the user holds. */
export function permissionsForRoles(roles: readonly Role[]): Permission[] {
  return [...new Set(roles.flatMap((role) => ROLE_PERMISSIONS[role]))];
}
