/**
 * Centralized machine-readable error codes returned to clients.
 */

/**
 * Clients switch on these and translate them locally, so they are part of the
 * public contract: rename one and every app breaks. Add, never repurpose.
 */
export const ERROR_CODE = {
  // generic
  INTERNAL: 'INTERNAL',
  VALIDATION: 'VALIDATION',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  FORBIDDEN: 'FORBIDDEN',
  UNAUTHORIZED: 'UNAUTHORIZED',
  RATE_LIMITED: 'RATE_LIMITED',
  UNAVAILABLE: 'UNAVAILABLE',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',

  // auth
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_OTP: 'INVALID_OTP',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_ATTEMPTS_EXCEEDED: 'OTP_ATTEMPTS_EXCEEDED',
  OTP_COOLDOWN: 'OTP_COOLDOWN',
  ACCOUNT_BLOCKED: 'ACCOUNT_BLOCKED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  SESSION_REVOKED: 'SESSION_REVOKED',

  // tenancy
  TENANT_NOT_RESOLVED: 'TENANT_NOT_RESOLVED',
  TENANT_INACTIVE: 'TENANT_INACTIVE',

  // orders
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
  ORDER_NOT_CANCELLABLE: 'ORDER_NOT_CANCELLABLE',
  ORDER_BELOW_MINIMUM: 'ORDER_BELOW_MINIMUM',
  // B2B: INVOICE needs an approved company with room in its credit limit.
  CREDIT_LIMIT: 'CREDIT_LIMIT',
  ORDERS_DISABLED: 'ORDERS_DISABLED',
  CART_EMPTY: 'CART_EMPTY',

  // catalog
  PRODUCT_UNAVAILABLE: 'PRODUCT_UNAVAILABLE',
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  STORE_CLOSED: 'STORE_CLOSED',
  PRICE_CHANGED: 'PRICE_CHANGED',

  // delivery & geo
  UNDELIVERABLE_ADDRESS: 'UNDELIVERABLE_ADDRESS',
  NO_COURIER_AVAILABLE: 'NO_COURIER_AVAILABLE',
  OFFER_EXPIRED: 'OFFER_EXPIRED',
  COURIER_BUSY: 'COURIER_BUSY',
  INVALID_HANDOVER_CODE: 'INVALID_HANDOVER_CODE',

  // payments
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_NOT_REFUNDABLE: 'PAYMENT_NOT_REFUNDABLE',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  WEBHOOK_SIGNATURE_INVALID: 'WEBHOOK_SIGNATURE_INVALID',

  // promotions
  COUPON_INVALID: 'COUPON_INVALID',
  COUPON_EXPIRED: 'COUPON_EXPIRED',
  COUPON_EXHAUSTED: 'COUPON_EXHAUSTED',

  // integrations
  PROVIDER_ERROR: 'PROVIDER_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE];
